#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [ "$LS_COLORS" -a -f /etc/DIR_COLORS ]; then
  eval $(dircolors /etc/DIR_COLORS)
fi

export PATH="$HOME/.nodebrew/current/bin:$PATH"
export PATH="$GOROOT/bin:$PATH"
export PATH="$PATH:$GOPATH/bin"
export PATH="$HOME/.jenv/shims:$PATH"
export PATH="$HOME/CyberAgent/dynalyst-mgmt-fm-tool:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="${HOME}/.scalaenv/bin:${PATH}"

export LSCOLORS=cxfxcxdxbxGxDxabagacad

eval "$(scalaenv init -)"
export GOPATH=~/go
export JENV_SHELL=zsh
export JENV_LOADED=1
unset JAVA_HOME
